In [1]:
import numpy as np


**Combining and Splitting Arrays**

In [2]:
print("Horizontal and Vertical Concatinaton")

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1)
print(arr2)

horizontal = np.hstack((arr1, arr2))

Vertical = np.vstack((arr1, arr2))

print(horizontal)
print(Vertical)



Horizontal and Vertical Concatinaton
[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]



vstack , hstack

In [3]:
print("Stack: ")

arr1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

arr2 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

print(arr1)
print(arr2)

v_stack = np.vstack((arr1, arr2))

h_stack = np.hstack((arr1, arr2))

print(v_stack)

print(h_stack)

Stack: 
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


**Split vsplit and hsplit**

In [4]:
print("Split Arrays")

arr1 = np.array([
    [1 , 2],
    [3 , 4],
    [5 , 6]
])

arr2 = np.array([
    [7 , 8 , 9 , 10 , 11 , 12],
    [13 , 14 , 15 , 16 , 17 , 18]
])

print("Arr1: ",arr1)
print("Arr2: ",arr2)

v_split = np.vsplit(arr1 , 3)

h_split = np.hsplit(arr2, 3)

print(v_split)

print(h_split)

Split Arrays
Arr1:  [[1 2]
 [3 4]
 [5 6]]
Arr2:  [[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[ 7,  8],
       [13, 14]]), array([[ 9, 10],
       [15, 16]]), array([[11, 12],
       [17, 18]])]


**Flattern and Reshape 3D Array**

In [5]:
print("Flattern and Reshape 3D Array")

arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr_3d)

print(arr_3d.shape) # check shape

flat_arr = arr_3d.flatten()

print(arr_3d)

print(flat_arr)

reshape = flat_arr.reshape(arr_3d.shape)# reshape array

print(reshape)



Flattern and Reshape 3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
